name: Run Java Tests

on:
  workflow_dispatch:
    inputs:
      suite:
        description: "Suite name"
        default: "testng.xml"

jobs:
  set-params:
    runs-on: ubuntu-latest
    outputs:
      suite: ${{ steps.setup-parameters.outputs.suite }}
    steps:
      - name: Setup parameters
        id: setup-parameters
        run: |
          echo "suite=${{ inputs.suite }}" >> $GITHUB_OUTPUT

  run-tests:
    needs: set-params
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'sapmachine'
          java-version: '21'
          cache: 'maven'

      - name: Build project
        run: |
          mvn clean install -D skipTests
