name: Run Java Tests

on:
  workflow_dispatch:
    inputs:
      suite:
        description: "Suite name"
        default: "testng.xml"

jobs:
  set-params:
    runs-on: ubuntu-latest
    outputs:
      suite: ${{ steps.setup-parameters.outputs.suite }}
    steps:
      - name: Setup parameters
        id: setup-parameters
        run: |
          echo "suite=${{ inputs.suite }}" >> $GITHUB_OUTPUT

  run-tests:
    needs: set-params
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'sapmachine'
          java-version: '21'
          cache: 'maven'
      
      - name: Install Chrome and Chromedriver
        run: |
          sudo apt update
          curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb
          google-chrome --version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Chrome version is $CHROME_VERSION"
          curl -O https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/
          rm chromedriver-linux64.zip
          chmod +x /usr/bin/chromedriver
          which google-chrome

      - name: Build project
        run: |
          mvn clean install -D skipTests
      
      - name: Run tests
        run: |
          mvn test -Dsuite=${{ needs.set-params.outputs.suite }} 
